name: Build and test

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Image
      run: docker build . --file Dockerfile --tag appuio/example-php-docker-helloworld:latest
    - name: Run the Container
      run: docker run -d --publish 8080:8080 appuio/example-php-docker-helloworld:latest
    - name: Test the app
      run: sleep 11 && curl -f localhost:8080/health/
     
